// src/lib/components/animations/ScrollProgress.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { browser } from '$app/environment';

  let progress = $state(0);
  let rafId: number;

  function updateProgress() {
    const scrollTop = window.scrollY;
    const docHeight = document.documentElement.scrollHeight - window.innerHeight;
    progress = docHeight > 0 ? Math.round((scrollTop / docHeight) * 100) : 0;
  }

  function onScroll() {
    cancelAnimationFrame(rafId);
    rafId = requestAnimationFrame(updateProgress);
  }

  onMount(() => {
    if (!browser) return;
    updateProgress();
    window.addEventListener('scroll', onScroll, { passive: true });
  });

  onDestroy(() => {
    if (!browser) return;
    window.removeEventListener('scroll', onScroll);
    cancelAnimationFrame(rafId);
  });
</script>

{#if browser}
<div class="fixed bottom-6 right-6 z-40 flex flex-col items-center gap-2" aria-hidden="true">
  <span class="text-[0.6875rem] tabular-nums text-[var(--text-2)] tracking-[0.04em] leading-none select-none w-8 text-center">
    {progress}%
  </span>
</div>
{/if}

// src/lib/components/animations/ScrollProgress.tsx
import { useState, useEffect, useRef } from 'react';

export default function ScrollProgress() {
  const [progress, setProgress] = useState(0);
  const rafId = useRef(0);

  useEffect(() => {
    function updateProgress() {
      const scrollTop = window.scrollY;
      const docHeight = document.documentElement.scrollHeight - window.innerHeight;
      setProgress(docHeight > 0 ? Math.round((scrollTop / docHeight) * 100) : 0);
    }

    function onScroll() {
      cancelAnimationFrame(rafId.current);
      rafId.current = requestAnimationFrame(updateProgress);
    }

    updateProgress();
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => {
      window.removeEventListener('scroll', onScroll);
      cancelAnimationFrame(rafId.current);
    };
  }, []);

  return (
    <div className="fixed bottom-8 right-6 z-40 flex flex-col items-center gap-2" aria-hidden="true">
      <span className="text-[0.6875rem] tabular-nums text-[var(--text-2)] tracking-[0.04em] leading-none select-none w-8 text-center">
        {progress}%
      </span>
    </div>
  );
}
