// src/routes/contact/+page.svelte
<script>
  import Menu from "$lib/components/layouts/Menu.svelte";
</script>
<main class="flex justify-between px-[5vw] py-[10vh] h-screen">
  <div class="flex flex-col items-start w-full min-h-screen text-white gap-8">
    <h1 class="text-3xl font-futura_pt tracking-wider">Say HELLO !</h1>
    <Menu/>
  </div>

  <div class="flex flex-col justify-center items-end w-full text-white gap-8">
    <ContactForm />
  </div>
</main>

// app/contact/page.tsx
import Menu from "@/components/layouts/Menu";
import ContactForm from "@/components/layouts/ContactForm";

export default function ContactPage() {
  return (
    <main className="flex justify-between px-[5vw] py-[10vh] h-screen">
      <div className="flex flex-col items-start w-full min-h-screen text-white gap-8">
        <h1 className="text-3xl font-futura tracking-wider">Say HELLO !</h1>
        <Menu />
      </div>

      <div className="flex flex-col justify-center items-end w-full text-white gap-8">
        <ContactForm />
      </div>
    </main>
  );
}
