// src/lib/components/layouts/Menu.svelte
<script lang="ts">
  import { page } from '$app/state';

  const links = [
    { href: '/', label: 'Home' },
    { href: '/about', label: 'About' },
    { href: '/lab', label: 'Lab' },
    { href: '/notes', label: 'Notes' },
    { href: '/contact', label: 'Contact' },
  ];
</script>

<nav class="flex flex-col gap-2">
  {#each links as link}
    <a
      href={link.href}
      class="font-futura_pt tracking-wider text-lg transition-opacity duration-200 {page.url.pathname === link.href ? 'text-white opacity-100' : 'text-white/40 hover:text-white/80'}"
    >
      {link.label}
    </a>
  {/each}
</nav>

// src/lib/components/layouts/Menu.tsx
import { Link, useLocation } from 'react-router-dom';

const links = [
  { href: '/', label: 'Home' },
  { href: '/about', label: 'About' },
  { href: '/lab', label: 'Lab' },
  { href: '/notes', label: 'Notes' },
  { href: '/contact', label: 'Contact' },
];

export default function Menu() {
  const { pathname } = useLocation();

  return (
    <nav className="flex flex-col gap-2">
      {links.map((link) => (
        <Link
          key={link.href}
          to={link.href}
          className={`font-futura_pt tracking-wider text-lg transition-opacity duration-200 ${
            pathname === link.href
              ? 'text-white opacity-100'
              : 'text-white/40 hover:text-white/80'
          }`}
        >
          {link.label}
        </Link>
      ))}
    </nav>
  );
}
