// src/lib/components/three/CameraRig.tsx
import { useRef, useEffect } from 'react';
import { useFrame, useThree } from '@react-three/fiber';
import { easing } from 'maath';

export default function CameraRig() {
  const { camera } = useThree();
  const pointer = useRef({ x: 0, y: 0 });

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      pointer.current.x = (e.clientX / window.innerWidth) * 2 - 1;
      pointer.current.y = -(e.clientY / window.innerHeight) * 2 + 1;
    };
    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  }, []);

  useFrame((_state, delta) => {
    easing.damp3(
      camera.position,
      [pointer.current.x * 5, pointer.current.y * 3, 50],
      0.3,
      delta
    );
    camera.lookAt(0, 0, 0);
  });

  return null;
}

// src/lib/components/three/CameraRig.svelte
<script lang="ts">
  import { useTask, useThrelte } from '@threlte/core';
  import { easing } from 'maath';
  import { onMount } from 'svelte';

  const { camera } = useThrelte();

  let pointer = { x: 0, y: 0 };

  onMount(() => {
    const handleMouseMove = (e: MouseEvent) => {
      pointer.x = (e.clientX / window.innerWidth) * 2 - 1;
      pointer.y = -(e.clientY / window.innerHeight) * 2 + 1;
    };
    window.addEventListener('mousemove', handleMouseMove);
    return () => window.removeEventListener('mousemove', handleMouseMove);
  });

  useTask((delta) => {
    easing.damp3(
      $camera.position,
      [pointer.x * 5, pointer.y * 3, 50],
      0.3,
      delta
    );
    $camera.lookAt(0, 0, 0);
  });
</script>
