// components/three/OrbitRing.tsx
"use client";

import { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export default function OrbitRing() {
  const groupRef = useRef<THREE.Group>(null);

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.x += 0.0007;
      groupRef.current.rotation.y += 0.0007;
      groupRef.current.rotation.z += 0.0007;
    }
  });

  return (
    <group ref={groupRef}>
      <mesh>
        <torusGeometry args={[16, 0.03, 80, 90, Math.PI * 3]} />
        <meshLambertMaterial color={0x4f4f4f} emissive={0x4f4f4f} flatShading />
      </mesh>
    </group>
  );
}

// src/lib/components/three/OrbitRing.svelte
<script lang="ts">
  import { T, useTask } from "@threlte/core";
  import * as THREE from "three";

  let group: THREE.Group;

  useTask(() => {
    if (group) {
      group.rotation.x += 0.0007;
      group.rotation.y += 0.0007;
      group.rotation.z += 0.0007;
    }
  });
</script>

<T.Group bind:ref={group}>
  <T.Mesh>
    <T.TorusGeometry args={[16, 0.03, 80, 90, Math.PI * 3]} />
    <T.MeshLambertMaterial color={0x4f4f4f} emissive={0x4f4f4f} flatShading />
  </T.Mesh>
</T.Group>
