// src/lib/components/three/Scene.tsx
import CameraRig from './CameraRig';
import Stars from './Stars';
import Sun from './Sun';
import OrbitRing from './OrbitRing';

export default function Scene() {
  return (
    <>
      <CameraRig />
      <Stars />
      <group position={[20, 0, 0]}>
        <Sun />
        <OrbitRing />
      </group>
      <directionalLight position={[4, 4, 4]} color={0x4f4f4f} />
      <directionalLight position={[-4, -4, -4]} color={0x4f4f4f} />
    </>
  );
}

// src/lib/components/three/Scene.svelte
<script lang="ts">
  import { T } from '@threlte/core';
  import CameraRig from './CameraRig.svelte';
  import Stars from './Stars.svelte';
  import Sun from './Sun.svelte';
  import OrbitRing from './OrbitRing.svelte';
</script>

<CameraRig />
<Stars />

<T.Group position={[10, 0, 0]}>
  <Sun />
  <OrbitRing />
</T.Group>

<T.DirectionalLight position={[4, 4, 4]} color={0x4f4f4f} />
<T.DirectionalLight position={[-4, -4, -4]} color={0x4f4f4f} />
