// src/lib/components/three/Sun.svelte
<script lang="ts">
  import { T, useTask } from "@threlte/core";
  import * as THREE from "three";

  let mesh: THREE.Mesh;

  useTask(() => {
    if (mesh) mesh.rotation.x += 0.001;
  });
</script>

<T.Mesh bind:ref={mesh}>
  <T.IcosahedronGeometry args={[5, 1]} />
  <T.MeshBasicMaterial color={0xf66120} wireframe />
</T.Mesh>

// src/lib/components/three/Sun.tsx
import { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

export default function Sun() {
  const meshRef = useRef<THREE.Mesh>(null);

  useFrame(() => {
    if (meshRef.current) meshRef.current.rotation.x += 0.001;
  });

  return (
    <mesh ref={meshRef}>
      <icosahedronGeometry args={[5, 1]} />
      <meshBasicMaterial color={0xf66120} wireframe />
    </mesh>
  );
}
