// src/lib/components/animations/FadeBlob.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import gsap from 'gsap';
  import { onMount } from 'svelte';

  let { href = '', class: className = '', children }: {
    href?: string;
    class?: string;
    children?: import('svelte').Snippet;
  } = $props();

  let container: HTMLDivElement;
  let blob: HTMLDivElement;
  let text: HTMLAnchorElement;

  onMount(() => {
    const speed = 0.3;
    gsap.set(blob, { opacity: 0, x: -5 });

    container.addEventListener('mouseenter', () => {
      gsap.to(text, { x: 5, duration: speed });
      gsap.to(blob, { opacity: 1, x: 0, duration: speed });
    });
    container.addEventListener('mouseleave', () => {
      gsap.to(text, { x: 0, duration: speed });
      gsap.to(blob, { opacity: 0, x: -5, duration: speed });
    });

    return () => gsap.killTweensOf([text, blob]);
  });

  function handleClick(e: MouseEvent) {
    e.preventDefault();
    goto(href);
  }
</script>

<div bind:this={container} class="py-1 flex items-center">
  <div bind:this={blob} class="w-1.5 h-1.5 bg-white rounded-full mr-1 opacity-0"></div>
  <a bind:this={text} {href} onclick={handleClick} class={className}>
    {@render children?.()}
  </a>
</div>

// components/animations/FadeBlob.tsx
"use client";

import { useEffect, useRef } from "react";
import { useRouter } from "next/navigation";
import gsap from "gsap";

interface FadeBlobProps {
  href?: string;
  className?: string;
  children?: React.ReactNode;
}

export default function FadeBlob({ href = "", className = "", children }: FadeBlobProps) {
  const router = useRouter();
  const containerRef = useRef<HTMLDivElement>(null);
  const blobRef = useRef<HTMLDivElement>(null);
  const textRef = useRef<HTMLAnchorElement>(null);

  useEffect(() => {
    const container = containerRef.current;
    const blob = blobRef.current;
    const text = textRef.current;
    if (!container || !blob || !text) return;

    const speed = 0.3;
    gsap.set(blob, { opacity: 0, x: -5 });

    const onEnter = () => {
      gsap.to(text, { x: 5, duration: speed });
      gsap.to(blob, { opacity: 1, x: 0, duration: speed });
    };
    const onLeave = () => {
      gsap.to(text, { x: 0, duration: speed });
      gsap.to(blob, { opacity: 0, x: -5, duration: speed });
    };

    container.addEventListener("mouseenter", onEnter);
    container.addEventListener("mouseleave", onLeave);

    return () => {
      container.removeEventListener("mouseenter", onEnter);
      container.removeEventListener("mouseleave", onLeave);
      gsap.killTweensOf([text, blob]);
    };
  }, []);

  function handleClick(e: React.MouseEvent) {
    e.preventDefault();
    router.push(href);
  }

  return (
    <div ref={containerRef} className="py-1 flex items-center">
      <div ref={blobRef} className="w-1.5 h-1.5 bg-white rounded-full mr-1 opacity-0" />
      <a ref={textRef} href={href} onClick={handleClick} className={className}>
        {children}
      </a>
    </div>
  );
}
